# Generated by Django 4.0.4 on 2022-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Digite um endereço de e-mail válido'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(error_messages={'unique': 'Usuário Já cadastrado'}, max_length=255, unique=True),
        ),
    ]
